services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: always
    command: redis-server --requirepass 1234
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  neo4j:
    image: neo4j:5.26-community
    container_name: neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/1234
      NEO4J_dbms_security_auth__minimum__password__length: 4
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

volumes:
  mongodb-data:
  redis-data:
  neo4j-data:
  neo4j-logs: